export const NAV_MENU = [
  {
    href: '/exp/dev',
    label: 'DEV',
    title: 'Dev work',
  },
  {
    href: '/exp/misc',
    label: 'MISC',
    title: 'Misc',
  },
  {
    href: '/exp/about',
    label: 'ABOUT',
    title: 'About',
  },
]

export const PORTFOLIO = [
  {
    _id: 0,
    colors: ['#3da5e1'],
    description: 'Agile Devtime in Polkadot',
    height: 60,
    href: 'https://morekudos.com/',
    label: 'Kudos Portal',
    logo: '/assets/images/kudos.png',
    title: 'Kudos Portal',
    width: 60,
  },
  // {
  //   _id: 1,
  //   colors: ['#000'],
  //   description: 'NFT-Centric Substrate Chain.',
  //   height: 40,
  //   href: 'https://bridge.ternoa.network/',
  //   label: 'Ternoa Bridge',
  //   logo: '/assets/svgs/ternoa.svg',
  //   title: 'Ternoa, NFT-Centric Substrate Chain.',
  //   width: 40,
  // },
  {
    _id: 1,
    colors: ['#6633cf'],
    description: 'The first Ternoa NFT marketplace.',
    height: 40,
    href: 'https://secret-stash.io/',
    label: 'Secret Stash',
    logo: '/assets/svgs/cube.svg',
    title: 'Secret Stash Marketplace',
    width: 40,
  },
  // {
  //   _id: 3,
  //   colors: ['#33568d'],
  //   description: 'Active Ternoa Validator nodes.',
  //   href: 'https://heracles.works/',
  //   label: 'HERACLES',
  //   logo: '/assets/svgs/heracles.svg',
  //   title: 'Active Ternoa Validator nodes.',
  // },
  // {
  //   _id: 3,
  //   colors: ['#009ddc'],
  //   description: 'Fuensanta R. Urien portfolio.',
  //   height: 40,
  //   href: 'https://fuensantarurien.com/',
  //   label: 'R. URIEN',
  //   logo: '/assets/svgs/rurien.svg',
  //   prefix: 'Fuensanta',
  //   title: 'Fuensanta R. Urien portfolio.',
  //   width: 40,
  // },
  {
    _id: 2,
    colors: ['#62ba49', '#fdb829', '#f6821f', '#df393d', '#973d97', '#009ddc'],
    description: "DON TELMO's web invasion.",
    href: '/',
    label: 'TELMO',
    logo: '/assets/svgs/alien.svg',
    prefix: 'DON',
    title: "Don Telmo's web invasion.",
  },
]
